### ISSUE TITLE
Plakat

### ISSUE THREAD

**Issue by xentec** [xentec/sync-party#1]

**Comment by knock93** [comment]
[Komponenten.pdf](https://github.com/xentec/sync-party/files/2091517/Komponenten.pdf)

**Comment by knock93** [comment]
[Komponenten.pdf](https://github.com/xentec/sync-party/files/2121543/Komponenten.pdf)

**Comment by knock93** [comment]
[Komponenten.pdf](https://github.com/xentec/sync-party/files/2123592/Komponenten.pdf)
